@BazarBin_HostAddress = http://localhost:5275
@DataSetId = 2

### List available data sets
GET {{BazarBin_HostAddress}}/datasets
Accept: application/json

### Send an AI prompt for a specific data set
POST {{BazarBin_HostAddress}}/prompt/{{DataSetId}}
Content-Type: application/json
Accept: application/json

{
  "prompt": "Most Expensive Product"
}
